
version: '3.8'
 
services:
  # Book Catalog Service
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://part3_qosn_user:NHOJbanl0jY1KYHLTihkwobeZOxg0GmJ@dpg-cs364dm8ii6s738grhag-a.oregon-postgres.render.com/part3_qosn
 
  # Inventory Management Service
  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://part3_qosn_user:NHOJbanl0jY1KYHLTihkwobeZOxg0GmJ@dpg-cs364dm8ii6s738grhag-a.oregon-postgres.render.com/part3_qosn
